%%%%%% Fisher Exact Test %%%%%%%% 
clear all; clc;
% Human-GEM (Version 1.11.0) was retrieved from the GitHub page
% (https://github.com/SysBioChalmers/Human-GEM) and saved as .mat file.
load('Human-GEM-Cobra.mat')
cobraHuman=model;

% Binary models generated by the iMAT algorithm were read. 
[num_h] = xlsread('file_name.xlsx');
[num_d] = xlsread('filen_name.xlsx');

H=num_h; % control group
AD=num_d; % AD group  (or AsymAD group)

[NumRows_H NumCols_H]=size(H);
[NumRows_AD NumCols_AD]=size(AD);

result_h=zeros(length(cobraHuman.rxns),2);
for i=1:length(cobraHuman.rxns);
   H_1= sum(H(i,:));
   H_0= NumCols_H-H_1 ;     
   result_h(i,:)= [H_0,H_1] ;
end
clear i;


result_d=zeros(length(cobraHuman.rxns),2);
for j=1:length(cobraHuman.rxns);
   D_1= sum(AD(j,:));
   D_0= NumCols_AD-D_1 ;    
   result_d(j,:)= [D_0,D_1];
end
clear j;


fisher_p=zeros(length(cobraHuman.rxns),2);
for k=1:length(cobraHuman.rxns);
 Temp_f=[result_h(k,1) , result_d(k,1); result_h(k,2), result_d(k,2)];
 [Temp_h,Temp_p,Temp_stats] = fishertest(Temp_f);
 fisher_p(k,1)=Temp_p;
 fisher_p(k,2)=Temp_stats.OddsRatio;
 %fisher_p(k,3)=Temp_odd;
 clear Temp_f Temp_h Temp_p Temp_stats Temp_odd 
end

 % p values and odd ratios were recorded.